"""Initial migration for database_connections table

Revision ID: 001_create_database_connections_table
Revises: 
Create Date: 2025-12-15 20:52:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_create_database_connections_table'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create database_connections table with UUID primary key
    op.create_table('database_connections',
        sa.Column('id', sa.UUID(), nullable=False, default=sa.text('gen_random_uuid()')),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('host', sa.String(length=255), nullable=False),
        sa.Column('port', sa.Integer(), nullable=False),
        sa.Column('database_name', sa.String(length=63), nullable=False),
        sa.Column('username', sa.String(length=63), nullable=False),
        sa.Column('password_hash', sa.Text(), nullable=False),
        sa.Column('salt', sa.Text(), nullable=False),
        sa.Column('ssl_mode', sa.String(length=20), nullable=True, default='require'),
        sa.Column('region', sa.String(length=50), nullable=True),
        sa.Column('cloud_provider', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for better performance
    op.create_index('idx_database_connections_is_active', 'database_connections', ['is_active'])
    op.create_index('idx_database_connections_cloud_provider', 'database_connections', ['cloud_provider'])
    op.create_index('idx_database_connections_region', 'database_connections', ['region'])
    
    # Create trigger function to auto-update updated_at timestamp
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$ language 'plpgsql';
    """)
    
    # Create trigger
    op.execute("""
        CREATE TRIGGER update_database_connections_updated_at 
            BEFORE UPDATE ON database_connections 
            FOR EACH ROW 
            EXECUTE FUNCTION update_updated_at_column();
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop trigger
    op.execute("DROP TRIGGER IF EXISTS update_database_connections_updated_at ON database_connections")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column()")
    
    # Drop indexes
    op.drop_index('idx_database_connections_region', table_name='database_connections')
    op.drop_index('idx_database_connections_cloud_provider', table_name='database_connections')
    op.drop_index('idx_database_connections_is_active', table_name='database_connections')
    
    # Drop table
    op.drop_table('database_connections')
    
    # ### end Alembic commands ###