"""Add PostgreSQL extensions support

Revision ID: 002_enable_postgresql_extensions
Revises: 001_create_database_connections_table
Create Date: 2025-12-15 20:53:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_enable_postgresql_extensions'
down_revision = '001_create_database_connections_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Enable pg_stat_statements extension for query performance tracking
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_stat_statements")
    
    # Enable pg_anon extension for data anonymization
    op.execute("CREATE EXTENSION IF NOT EXISTS anon")
    
    # Create view for frequently executed queries (slow queries)
    op.execute("""
        CREATE OR REPLACE VIEW slow_queries AS
        SELECT 
            query,
            calls,
            total_exec_time,
            mean_exec_time,
            stddev_exec_time,
            max_exec_time,
            min_exec_time
        FROM pg_stat_statements 
        WHERE mean_exec_time > 100  -- Queries taking more than 100ms on average
        ORDER BY mean_exec_time DESC
        LIMIT 20;
    """)
    
    # Create view for database statistics summary
    op.execute("""
        CREATE OR REPLACE VIEW database_stats_summary AS
        SELECT 
            'total_queries' as metric_name,
            SUM(calls) as metric_value,
            'Total number of queries executed' as description
        FROM pg_stat_statements
        UNION ALL
        SELECT 
            'avg_execution_time' as metric_name,
            AVG(mean_exec_time) as metric_value,
            'Average query execution time in milliseconds' as description
        FROM pg_stat_statements
        UNION ALL
        SELECT 
            'total_execution_time' as metric_name,
            SUM(total_exec_time) as metric_value,
            'Total time spent executing queries in milliseconds' as description
        FROM pg_stat_statements;
    """)
    
    # Create function to get query performance metrics
    op.execute("""
        CREATE OR REPLACE FUNCTION get_query_performance_stats(
            limit_entries INTEGER DEFAULT 10
        ) RETURNS TABLE(
            query TEXT,
            calls BIGINT,
            total_exec_time DOUBLE PRECISION,
            mean_exec_time DOUBLE PRECISION,
            rows_per_call DOUBLE PRECISION
        ) AS $$
        BEGIN
            RETURN QUERY
                SELECT 
                    LEFT(query, 100) as query,  -- Truncate very long queries
                    calls,
                    total_exec_time,
                    mean_exec_time,
                    CASE 
                        WHEN calls > 0 THEN total_exec_time / calls 
                        ELSE 0 
                    END as rows_per_call
                FROM pg_stat_statements 
                ORDER BY mean_exec_time DESC
                LIMIT limit_entries;
        END;
        $$ LANGUAGE plpgsql;
    """)
    
    # Create function to anonymize sample data for development
    op.execute("""
        CREATE OR REPLACE FUNCTION anonymize_sensitive_data(
            input_data TEXT,
            anonymization_level INTEGER DEFAULT 1  -- 1: partial, 2: full
        ) RETURNS TEXT AS $$
        BEGIN
            -- Use pg_anon extension functions if available
            IF anonymization_level = 1 THEN
                -- Partial anonymization (mask middle characters)
                RETURN CASE 
                    WHEN LENGTH(input_data) <= 4 THEN '****'
                    WHEN LENGTH(input_data) <= 8 THEN LEFT(input_data, 2) || '****' || RIGHT(input_data, 2)
                    ELSE LEFT(input_data, 4) || '****' || RIGHT(input_data, 4)
                END;
            ELSIF anonymization_level = 2 THEN
                -- Full anonymization
                RETURN 'ANONYMIZED';
            ELSE
                RETURN input_data;
            END IF;
        END;
        $$ LANGUAGE plpgsql;
    """)
    
    # Grant appropriate permissions
    op.execute("GRANT SELECT ON slow_queries TO PUBLIC")
    op.execute("GRANT SELECT ON database_stats_summary TO PUBLIC")
    op.execute("GRANT EXECUTE ON FUNCTION get_query_performance_stats TO PUBLIC")
    op.execute("GRANT EXECUTE ON FUNCTION anonymize_sensitive_data TO PUBLIC")
    
    # Create indexes on pg_stat_statements for better performance
    op.create_index('idx_pg_stat_statements_mean_time', 'pg_stat_statements', ['mean_exec_time'])
    op.create_index('idx_pg_stat_statements_calls', 'pg_stat_statements', ['calls'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('idx_pg_stat_statements_calls')
    op.drop_index('idx_pg_stat_statements_mean_time')
    
    # Drop functions and views
    op.execute("DROP FUNCTION IF EXISTS anonymize_sensitive_data()")
    op.execute("DROP FUNCTION IF EXISTS get_query_performance_stats()")
    op.execute("DROP VIEW IF EXISTS database_stats_summary")
    op.execute("DROP VIEW IF EXISTS slow_queries")
    
    # Drop extensions
    op.execute("DROP EXTENSION IF EXISTS anon")
    op.execute("DROP EXTENSION IF EXISTS pg_stat_statements")
    
    # ### end Alembic commands ###